/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        verPaciente.setVisible(false);
        verSecretaria.setVisible(false);
        verDoctor.setVisible(false);
        String opc = (String) Login.comElige.getSelectedItem();
        if (opc == "PACIENTE") {
            verPaciente.setVisible(true);
        } else if (opc == "SECRETARIA") {
            verSecretaria.setVisible(true);
        } else if (opc == "DOCTOR") {
            verDoctor.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        verPaciente = new javax.swing.JMenu();
        pacOpciones = new javax.swing.JMenuItem();
        verDoctor = new javax.swing.JMenu();
        docOpciones = new javax.swing.JMenuItem();
        verSecretaria = new javax.swing.JMenu();
        secOpciones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        salCerrar = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        verPaciente.setMnemonic('f');
        verPaciente.setText("PACIENTE");

        pacOpciones.setMnemonic('o');
        pacOpciones.setText("OPCIONES");
        pacOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacOpcionesActionPerformed(evt);
            }
        });
        verPaciente.add(pacOpciones);

        menuBar.add(verPaciente);

        verDoctor.setMnemonic('e');
        verDoctor.setText("DOCTOR");

        docOpciones.setText("OPCIONES");
        docOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docOpcionesActionPerformed(evt);
            }
        });
        verDoctor.add(docOpciones);

        menuBar.add(verDoctor);

        verSecretaria.setMnemonic('h');
        verSecretaria.setText("SECRETARIA");

        secOpciones.setText("OPCIONES");
        secOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secOpcionesActionPerformed(evt);
            }
        });
        verSecretaria.add(secOpciones);

        menuBar.add(verSecretaria);

        jMenu3.setText("SALIR");

        salCerrar.setText("CERRAR");
        salCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salCerrarActionPerformed(evt);
            }
        });
        jMenu3.add(salCerrar);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacOpcionesActionPerformed
        VentanaPaciente vp = new VentanaPaciente();
        desktopPane.add(vp);
    }//GEN-LAST:event_pacOpcionesActionPerformed

    private void salCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salCerrarActionPerformed
        Login.main(null);
        this.dispose();
    }//GEN-LAST:event_salCerrarActionPerformed

    private void docOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docOpcionesActionPerformed
        VentanaDoctor vd = new VentanaDoctor();
        desktopPane.add(vd);
    }//GEN-LAST:event_docOpcionesActionPerformed

    private void secOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secOpcionesActionPerformed
        VentanaSecretaria vs = new VentanaSecretaria();
        desktopPane.add(vs);
    }//GEN-LAST:event_secOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem docOpciones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pacOpciones;
    private javax.swing.JMenuItem salCerrar;
    private javax.swing.JMenuItem secOpciones;
    public static javax.swing.JMenu verDoctor;
    public static javax.swing.JMenu verPaciente;
    public static javax.swing.JMenu verSecretaria;
    // End of variables declaration//GEN-END:variables

}
